INSERT INTO sources (NAME, link, subscribers, platform, category, description, contact)
VALUES
	("CodeCamp", "t.me/codecamp", "274179", "Telegram", "IT", "Канал про различные IT новости", "TG: @todaycast"),
	("Эксплойт", "https://t.me/exploitex", "1739643", "Telegram", "IT", "Новости о технологиях, новинках в сфере IT, лайфхаки и информация о криптовалюте.", "TG: @todaycast"),
	("Бэкдор", "https://t.me/whackdoor", "1615938", "Telegram", "IT", "Информация о технологиях и информационной безопасности.", "TG: @NeuroNeron"),
	("Утечки информации", "https://t.me/dataleak", "123092", "Telegram", "IT", "Авторские статьи про утечки данных и кибербезопасность.", "dataleak@mail.ru"),
	("Tproger", "https://t.me/tproger_official", "81325", "Telegram", "IT", "Полезная информация, новости и мемы для программистов.", "TG: @tproger_sales_bot"),
	("UniLecs", "https://t.me/unilecs", "18459", "Telegram", "IT", "Задачи и примеры по алгоритмизации и программированию, курсы и лекции.", "TG: @dashalvv"),
	("TechRocks", "https://t.me/techrocks", "15707", "Telegram", "IT", "Легкие статьи о мире IT-технологий и программировании.", "TG: @anothertechrock"),
	("Библиотека программиста", "https://t.me/proglibrary", "89008", "Telegram", "IT", "Обзоры книг, видеолекции и образовательные статьи для программистов.", "TG: @proglibrary_feedback_bot"),
	("Nuances of programming", "https://t.me/nuancesprog", "69530", "Telegram", "IT", "Образовательные статьи, лайфхаки по собеседованиям и актуальные курсы.", "TG: @ramilkr"),
	("Machinelearning Big Data AI News Channel","https://t.me/ai_machinelearning_big_data","93765","Telegram","IT","Новости о машинном обучении, нейронных сетях и больших данных.","TG: @haarrp"),
	("iOS Good Reads","https://t.me/iOSGoodReads","1800","Telegram","IT","Канал о разработке под iOS с полезными материалами.","iosgoodreads@mail.ru"),
	("StartAndroid","https://t.me/startandroid","10650","Telegram","IT","Канал о разработке под Android с советами и статьями.","https://startandroid.ru/ru/about/reklama.html"),
	("Tech Guide", "https://t.me/TechGuide", "4500", "Telegram", "IT", "Новости о мобильных и веб-технологиях.", "techguide@mail.ru"),
	("GetIT Jobs", "https://t.me/Getitrussia", "6000", "Telegram",  "IT","Топовые объявления на удаленку в сфере информационных технологий.","getitjobs@mail.ru"),
	("Remote IT (Inflow)",  "https://t.me/Remoteit","3500","Telegram","IT","Вакансии для удаленной работы в различных проектах из сферы информационных технологий.","remoteit@mail.ru"),
	("Machine Learning & AI News","https://t.me/machinelearningnews","8000","Telegram","IT","Актуальные новости из мира машинного обучения и ИИ.","mlnews@mail.ru"),
	("Digital Marketing Insights","https://t.me/Marketing_PR_IT","2200","Telegram","IT","Обсуждение важнейших вопросов из жизни пиарщиков и маркетологов ИТ-компаний.","marketinginsights@mail.ru"),
	("Cybersecurity News Channel","https://t.me/cybersecuritynewschannel","1500","Telegram","IT","Новости кибербезопасности и защиты данных.","cybernews@mail.ru"),
	("Software Development Tips & Tricks","https://t.me/softwaredevtipsandtricks","1000","Telegram","IT","Советы по разработке программного обеспечения.","devtips@mail.ru"),
	("Frontend Developer Community","https://t.me/frontenddevcommunity","2800","Telegram","IT","Сообщество фронтенд-разработчиков с полезными ресурсами.","frontendcommunity@mail.ru"),
	("DevOps & SRE News Channel","https://t.me/devopsnewschannel","1200","Telegram","IT","Новости и ресурсы по DevOps и Site Reliability Engineering.","devopsnews@mail.ru"),
	("NetworkChuck", "https://www.youtube.com/c/NetworkChuck", "1580000", "YouTube", "IT", "Канал о сетевых технологиях, кибербезопасности и облачных вычислениях.", "info@networkchuck.com"),
	("freeCodeCamp.org", "https://www.youtube.com/c/Freecodecamp", "3500000", "YouTube", "IT", "Образовательные видео по программированию и разработке веб-приложений.", "contact@freecodecamp.org"),
	("The Coding Train", "https://www.youtube.com/c/TheCodingTrain", "1630000", "YouTube", "IT", "Канал с уроками по программированию и визуализации данных.", "thecodingtrain@gmail.com"),
	("Traversy Media", "https://www.youtube.com/c/TraversyMedia", "2080000", "YouTube", "IT", "Широкий спектр уроков по веб-разработке и современным технологиям.", "brad@traversymedia.com"),
	("John Savill's Technical Training", "https://www.youtube.com/c/JohnSavillTech", "150000", "YouTube", "IT", "Подробные уроки по облачным технологиям и IT-инфраструктуре.", "john.savill@outlook.com"),
	("Professor Messer", "https://www.youtube.com/c/professormesser", "500000", "YouTube", "IT", "Канал для подготовки к сертификациям CompTIA.", "contact@professormesser.com"),
	("ITProTV", "https://www.youtube.com/c/ITProTV", "100000", "YouTube", "IT", "Разнообразные курсы по IT, включая сетевые технологии и кибербезопасность.", "support@itpro.tv"),
	("CBT Nuggets", "https://www.youtube.com/c/CBTNuggets", "200000", "YouTube", "IT", "Короткие видео на темы IT, включая облачные технологии и безопасность.", "contact@cbt-nuggets.com"),
	("Fireship", "https://www.youtube.com/c/Fireship", "2190000", "YouTube", "IT", "Эффективные уроки по программированию и новостям технологий.", "fireship.io@gmail.com"),
	("Computerphile", "https://www.youtube.com/c/Computerphile", "2400000", "YouTube",  "IT","Образовательные видео о компьютерных науках и технологиях.","contact@computerphile.com"),
	("Unbox Therapy","https://www.youtube.com/user/unboxtherapy","21400000","YouTube","IT","Обзоры новейших гаджетов и технологий.","contact@unboxtherapy.com"),
	("Marques Brownlee (MKBHD)","https://www.youtube.com/user/marquesbrownlee","17800000","YouTube","IT","Обзоры технологий, смартфонов и гаджетов.","contact@mkbhd.com"),
	("TechLinked","https://www.youtube.com/c/TechLinked","3500000","YouTube","IT","Краткие новости технологий и обновления.","techlinked@gmail.com"),
	("The Net Ninja","https://www.youtube.com/c/TheNetNinja","1140000","YouTube","IT","Уроки по веб-разработке, включая JavaScript и Node.js.","thenetninja@gmail.com"),
	("Web Dev Simplified","https://www.youtube.com/c/WebDevSimplified","1320000","YouTube","IT","Простые уроки по веб-разработке.","webdevsimplified@gmail.com"),
	("Tech With Tim","https://www.youtube.com/c/TechWithTim","1240000","YouTube","IT","Уроки по программированию на Python и JavaScript.","techwithtim@gmail.com"),
	("Google Tech Talks","https://www.youtube.com/user/GoogleTechTalks","343000","YouTube","IT","Глубокие обсуждения технологий и науки.","googletechtalks@gmail.com"),
	("freeCodeCamp", "https://www.instagram.com/freecodecamp/", "2500000", "Instagram", "IT", "Образовательные материалы по программированию и технологиям.", "contact@freecodecamp.org"),
	("The Verge", "https://www.instagram.com/verge/", "1000000", "Instagram", "IT", "Новости технологий и обзоры продуктов.", "contact@theverge.com"),
	("TechCrunch", "https://www.instagram.com/techcrunch/", "1200000", "Instagram", "IT", "Последние новости стартапов и технологий.", "tips@techcrunch.com"),
	("Linus Tech Tips", "https://www.instagram.com/linustech/", "2000000", "Instagram", "IT", "Обзоры технологий и компьютерного оборудования.", "linus@linusmediagroup.com"),
	("Marques Brownlee", "https://www.instagram.com/mkbhd/", "15000000", "Instagram", "IT", "Обзоры технологий и гаджетов.", "contact@mkbhd.com"),
	("Gizmodo", "https://www.instagram.com/gizmodo/", "1500000", "Instagram", "IT", "Новости и обзоры технологий.", "tips@gizmodo.com"),
	("CNET", "https://www.instagram.com/cnet/", "1000000", "Instagram", "IT", "Обзоры технологий и советы по покупке.", "contact@cnet.com"),
	("NASA", "https://www.instagram.com/nasa/", "60000000", "Instagram", "IT", "Новости и изображения из космоса.", "nasa@space.com"),
	("Android Authority", "https://www.instagram.com/androidauthority/", "1200000", "Instagram", "IT", "Обзоры Android-устройств и технологий.", "contact@androidauthority.com"),
	("Digital Trends", "https://www.instagram.com/digitaltrends/", "800000", "Instagram", "IT", "Новости технологий и обзоры продуктов.","contact@digitaltrends.com"),
	("@techwithtim","https://www.tiktok.com/@techwithtim","1240000","TikTok","IT","Уроки по программированию на Python и JavaScript.","techwithtim@gmail.com"),
	("@codingwithjohn","https://www.tiktok.com/@codingwithjohn","50000","TikTok","IT","Уроки по программированию для начинающих.","codingwithjohn@gmail.com"),
	("@data_science_guy","https://www.tiktok.com/@data_science_guy","30000","TikTok","IT","Советы по науке о данных и аналитике.","datascienceguy@gmail.com"),
	("@cybersecurity_expert","https://www.tiktok.com/@cybersecurity_expert","40000","TikTok","IT","Советы по кибербезопасности.","cybersecurityexpert@gmail.com"),
	("@devops_dude","https://www.tiktok.com/@devops_dude","20000","TikTok","IT","Обучение DevOps и облачным технологиям.","devopsdude@gmail.com"),
	("@frontend_freaks","https://www.tiktok.com/@frontend_freaks","35000","TikTok","IT","Уроки по фронтенд-разработке.","frontendfreaks@gmail.com"),
	("IT News", "https://vk.com/itnews", "500000", "VK", "IT", "Последние новости из мира технологий и IT.", "itnews@vk.com"),
	("Программирование на Python", "https://vk.com/python", "300000", "VK", "IT", "Сообщество для любителей программирования на Python.", "pythoncommunity@vk.com"),
	("Кибербезопасность VK", "https://vk.com/cybersecurity", "250000", "VK", "IT", "Новости и советы по кибербезопасности.", "cybersecurity@vk.com"),
	("Хакеры и безопасность", "https://vk.com/hackers_security", "150000", "VK", "IT", "Обсуждения о хакерских атаках и методах защиты.", "hackers@vk.com"),
	("Разработка игр VK", "https://vk.com/gamedev", "200000", "VK", "IT", "Сообщество разработчиков игр.", "gamedev@vk.com"),
	("Web-разработка", "https://vk.com/webdev", "400000", "VK", "IT", "Уроки и советы по веб-разработке.", "webdev@vk.com"),
	("Системное администрирование", "https://vk.com/sysadmin", "180000", "VK", "IT", "Ресурсы и советы для системных администраторов.", "sysadmin@vk.com"),
	("Мобильная разработка VK", "https://vk.com/mobiledev", "120000", "VK", "IT", "Обсуждение мобильной разработки и технологий.", "mobiledev@vk.com"),
	("Искусственный интеллект и машинное обучение", "https://vk.com/ai_ml", "220000", "VK", "IT", "Новости и статьи об ИИ и машинном обучении.", "aiml@vk.com"),
	("Технологии будущего VK",  "https://vk.com/futuretech","350000","VK","IT","Обсуждение новых технологий и их будущего.","futuretech@vk.com"),
	("DevOps Community","https://vk.com/devopscommunity","300000","VK","IT","Сообщество DevOps-специалистов.","devopscommunity@vk.com"),
	("Frontend Developers","https://vk.com/frontenddevs","250000","VK","IT","Обсуждение фронтенд-разработки и технологий.","frontenddevs@vk.com"),
	("Backend Developers","https://vk.com/backenddevs","200000","VK","IT","Сообщество бэкенд-разработчиков.","backenddevs@vk.com"),
	("Open Source Projects","https://vk.com/opensourceprojects","150000","VK","IT","Проекты с открытым исходным кодом.","opensourceprojects@vk.com"),
	("Тестирование ПО VK","https://vk.com/softwaretesting","180000","VK","IT","Новости и ресурсы по тестированию программного обеспечения.","softwaretesting@vk.com"),
	("Курсы по программированию","https://vk.com/programmingcourses","300000","VK","IT","Обучающие курсы по программированию.","programmingcourses@vk.com"),
	("Информационные технологии в бизнесе","https://vk.com/itbusiness","220000","VK","IT","Использование IT в бизнесе и управлении.","itbusiness@vk.com"),
	("Гаджеты и технологии","https://vk.com/gadgetsandtech","280000","VK","IT","Обзоры новейших гаджетов и технологий.","gadgetsandtech@vk.com"),
	("Блогеры о технологиях ","https://vk.com/techbloggers ","150000 ","VK ","IT ","Обзоры блогеров о последних технологиях.","techbloggers@vk.com "),
	("Технологические стартапы ","https://vk.com/startups ","170000 ","VK ","IT ","Новости о стартапах в сфере технологий.","startups@vk.com "),
	("Технологии будущего", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5d", "15000", "Yandex Dzen", "IT", "Новости и инновации в области технологий.", "techfuture@yandex.ru"),
	("Программирование для всех", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5e", "12000", "Yandex Dzen", "IT", "Образовательные материалы по программированию.", "programmingforall@yandex.ru"),
	("Кибербезопасность", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5f", "8000", "Yandex Dzen", "IT", "Советы и новости по кибербезопасности.", "cybersecurity@yandex.ru"),
	("Искусственный интеллект", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5g", "20000", "Yandex Dzen", "IT", "Статьи и исследования в области ИИ.", "ai@yandex.ru"),
	("Облачные технологии", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5h", "10000", "Yandex Dzen", "IT", "Новости и разработки в облачных технологиях.", "cloudtech@yandex.ru"),
	("Технологии в образовании", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5i", "13000", "Yandex Dzen", "IT", "Как технологии меняют образование.", "edutech@yandex.ru"),
	("Мобильная разработка", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5j", "9000", "Yandex Dzen", "IT", "Советы по разработке мобильных приложений.", "mobiledev@yandex.ru"),
	("Frontend разработка", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5k", "11000", "Yandex Dzen", "IT", "Уроки и советы по фронтенд-разработке.", "frontend@yandex.ru"),
	("Backend разработка", "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5l", "15000", "Yandex Dzen", "IT", "Ресурсы для бэкенд-разработчиков.", "backend@yandex.ru"),
	("Разработка игр",  "https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7f5m","25000","Yandex Dzen","IT","Новости и советы по разработке игр.","gamedev@yandex.ru"),
	("Тестирование ПО","https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7n","18000","Yandex Dzen","IT","Статьи по тестированию программного обеспечения.","softwaretesting@yandex.ru"),
	("DevOps практики","https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7o","22000","Yandex Dzen","IT","Советы и инструменты для DevOps.","devops@yandex.ru"),
	("Наука о данных","https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7p","30000","Yandex Dzen","IT","Ресурсы и статьи по Data Science.","datascience@yandex.ru"),
	("Криптовалюты и блокчейн","https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7q","40000","Yandex Dzen","IT","Новости и аналитика криптовалют.","crypto@yandex.ru"),
	("Интернет вещей (IoT)","https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7r","15000","Yandex Dzen","IT","Статьи о технологиях IoT.","iot@yandex.ru"),
	("Технологические стартапы","https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7s","20000","Yandex Dzen","IT","Новости о стартапах в сфере технологий.","startups@yandex.ru"),
	("Этика технологий","https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7t","12000","Yandex Dzen","IT","Обсуждение этических вопросов в технологиях.","ethics@yandex.ru"),
	("Финансовые технологии (FinTech)","https://Dzen.yandex.ru/id/601f6e8f9f8d4a4e1e1b7u","22000","Yandex Dzen","IT","Новости и тренды в FinTech.","fintech@yandex.ru"),
	("Обучение программированию для детей ","https://Dzen.yandex.ru/id/601fe0c2c0c3af001fa3c3c3 ","10000 ","Yandex Dzen ","IT ","Ресурсы для обучения детей программированию.","kidsprogramming@yandex.ru "),
	("Женщины в IT ","https://Dzen.yandex.ru/id/601fe0c2c0c3af001fa3c3c3 ","8000 ","Yandex Dzen ","IT ","Поддержка женщин в сфере технологий.","womenintech@yandex.ru ")